running: local
domain: http://localhost:8080

spring:
  profiles:
    include: common
    active: local
  h2:
    console:
      enabled: true
      path: /h2
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true
#        highlight_sql: true
#        use_sql_comments: true
logging:
  level:
    org.hibernate.SQL: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace
  com:
    amazonaws:
      util:
        EC2MetadataUtils: error
cloud:
  aws:
    credentials:
      accessKey: ${aws_access_key_id}
      secretKey: ${aws_secret_access_key}
    s3:
      bucket: seoham-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
mail:
  address:
    admin: admin@gmail.com