running: dev
domain: ec2-13-209-41-214.ap-northeast-2.compute.amazonaws.com:8080

spring:
  profiles:
    include: common
    active: dev
  datasource:
    url: ${datasource_url}
    username: ${datasource_username}
    password: ${datasource_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
          matching-strategy: ant_path_matcher


#  jpa:
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
logging:
  level:
    org.hibernate.SQL: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace
cloud:
  aws:
    credentials:
      accessKey: ${aws_access_key_id}
      secretKey: ${aws_secret_access_key}
    s3:
      bucket: seoham-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
mail:
  address:
    admin: admin@gmail.com
